version: '3.2'

networks:
  binghe-cluster-apps:
    driver: overlay

volumes:
  prometheus_data: {}
services:
  polaris:
    image: polaris
    container_name: polaris
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8081:8081
      - 20880:20880
    networks:
      - binghe-cluster-apps
    restart: on-failure




